[package]
name = "tokio-test"
version = "0.1.0"
edition = "2021"

[dependencies]
# tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
tokio = { version = "1", features = ["full"] }
